[package]
name = "aleo-setup-integration-test"
version = "0.1.0"
description = "Integration test for aleo-setup and aleo-setup-coordinator"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"

[dependencies]
color-eyre = "0.5"
eyre = "0.6"
regex = "1.4"
subprocess = "0.2.6"
tracing = "0.1"
tracing-error = "0.1"
tracing-subscriber = "0.2"
mpmc-bus = { path = "../mpmc-bus/", version = "0.1" }

[profile.dev.package.backtrace]
opt-level = 3